swagger: '2.0'
info:
  title: Vacancy.io API
  description: A REST API for Vacancy.io
  version: 1.0.0
host: vacancy.io
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /jobs:
    get:
      summary: Get all jobs
      description: |
        The jobs endpoint returns all jobs
      tags:
        - Jobs
      responses:
        '200':
          description: An array of jobs
        default:
          description: Unexpected error